# -*- coding: utf-8 -*-
"""Loan_Approval_ Train_and_Export.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZ01PbeC-NPUE2JpsYYVo3h0C5bchfVE
"""

import streamlit as st
import pandas as pd
import joblib

# ==========================================
# 1. SETUP & MODEL LOADING
# ==========================================
st.set_page_config(page_title="Bank Loan Approval System", page_icon="🏦", layout="centered")

@st.cache_resource
def load_models():
    # Load the exported joblib files
    preprocessor = joblib.load('loan_preprocessor.joblib')
    model = joblib.load('loan_tree_model.joblib')
    return preprocessor, model

preprocessor, model = load_models()

# ==========================================
# 2. APP HEADER
# ==========================================
st.title("🏦 Automated Loan Approval Prediction")
st.markdown("Enter the applicant's details below to predict whether their loan application will be approved using an optimized Decision Tree algorithm.")
st.divider()

# ==========================================
# 3. USER INPUT FORM
# ==========================================
st.subheader("Applicant Information")

col1, col2 = st.columns(2)

with col1:
    st.markdown("**Personal Details**")
    education = st.selectbox("Education", ["Graduate", "Not Graduate"])
    marital_status = st.selectbox("Marital Status", ["Married", "Single"])
    dependents = st.selectbox("Dependents", ["0", "1", "2", "3+"])
    property_area = st.selectbox("Property Area", ["Urban", "Semiurban", "Rural"])

with col2:
    st.markdown("**Financial & Loan Details**")
    employment_type = st.selectbox("Employment Type", ["Salaried", "Self Employed"])
    applicant_income = st.number_input("Applicant Income ($)", min_value=0, value=50000, step=1000)
    coapplicant_income = st.number_input("Coapplicant Income ($)", min_value=0, value=0, step=1000)

st.markdown("**Loan Request**")
col3, col4, col5 = st.columns(3)
with col3:
    loan_amount = st.number_input("Loan Amount Requested ($)", min_value=1000, value=150000, step=5000)
with col4:
    # Most common loan terms in months
    loan_amount_term = st.selectbox("Loan Term (Months)", [12, 36, 60, 84, 120, 180, 240, 300, 360, 480], index=8)
with col5:
    # 1 is good history, 0 is bad/no history
    credit_history_mapped = st.selectbox("Credit History", ["Good (1.0)", "Poor/None (0.0)"])
    credit_history = 1.0 if "Good" in credit_history_mapped else 0.0

st.divider()

# ==========================================
# 4. PREDICTION LOGIC
# ==========================================
if st.button("Predict Loan Status", type="primary"):

    # 1. Package inputs exactly as they appear in the original CSV
    input_data = {
        'ApplicantIncome': applicant_income,
        'CoapplicantIncome': coapplicant_income,
        'LoanAmount': loan_amount,
        'Loan_Amount_Term': loan_amount_term,
        'CreditHistory': credit_history,
        'Education': education,
        'EmploymentType': employment_type,
        'MaritalStatus': marital_status,
        'Dependents': dependents,
        'PropertyArea': property_area
    }

    input_df = pd.DataFrame([input_data])

    try:
        # 2. Transform the raw inputs using the loaded preprocessor
        transformed_data = preprocessor.transform(input_df)

        # 3. Make the prediction
        prediction = model.predict(transformed_data)[0]
        probabilities = model.predict_proba(transformed_data)[0]

        # 4. Display Results
        st.subheader("Decision Engine Output")
        if prediction == 1:
            st.success("✅ **LOAN APPROVED**")
            st.write(f"Confidence Score: **{probabilities[1] * 100:.1f}%**")
        else:
            st.error("⚠️ **LOAN REJECTED**")
            st.write(f"Confidence Score: **{probabilities[0] * 100:.1f}%**")
            st.info("💡 **Insight:** Consider requesting a lower loan amount or increasing the term duration.")

    except Exception as e:
        st.error(f"An error occurred: {e}")